services:
  frontend:
    build:
      context: ./frontend
    ports:
      # - "80:80"  # Expose frontend on port 80
      - "5174:80"
    depends_on:
      - backend  # Wait for the backend to start

  backend:
    build:
      context: ./backend
    ports:
      - "5178:3001"  # Expose backend on port 3001
    volumes:
      - ./backend/users.db:/app/users.db  # Mount the SQLite database to persist it
